In [76]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/datasolve-us/sample_submission.csv
/kaggle/input/datasolve-us/train.csv
/kaggle/input/datasolve-us/test.csv


In [77]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"
import numpy as np
import warnings
warnings.filterwarnings('ignore')

np.set_printoptions(precision=3)
                    
import pandas as pd
import os

In [78]:
data1 = pd.read_csv("/kaggle/input/datasolve-us/train.csv")
test = pd.read_csv("/kaggle/input/datasolve-us/test.csv")

In [79]:
test_doc=list(test['document_text'])

In [80]:
data1['document_text']= data1['document_text'].str.lower()

In [81]:
spec_chars = ["!",'"',"#","%","&","'","(",")",
              "*","+",",","-",".","/",":",";","<",
              "=",">","?","@","[","\\","]","^","_",
              "`","{","|","}","~","–"]
for char in spec_chars:
    data1['document_text'] = data1['document_text'].str.replace(char, ' ')

In [82]:
data1['document_text'] = data1['document_text'].str.replace(r'\b\w\b', '').str.replace(r'\s+', ' ')
data1['document_text'] = data1['document_text'].str.replace('\d+', '')

In [83]:
data2 = data1.groupby('document_text')['cat_name'].apply(list)
data3=data2.to_frame().reset_index()
data4=tuple(data3['document_text'])
#data2= data1.groupby('document_text')

In [84]:
len(data2)

9103

In [86]:
print(data1['cat_name'])

0            Corporate Communications
1               Securities Settlement
2                           Antitrust
3               Securities Settlement
4                     Financial Crime
                     ...             
47097            Corporate Governance
47098    Monetary and Economic Policy
47099                           Fraud
47100                      Exemptions
47101                Fees and Charges
Name: cat_name, Length: 47102, dtype: object


In [87]:
labels=data3['cat_name']
print(labels)

0       [Securities Management, Regulatory Actions, Re...
1       [Market Risk, Financial Crime, Monetary and Ec...
2       [Examinations, Compliance Management, Delivery...
3       [Licensure and certification, Examinations, Re...
4         [Securities Clearing, Payments and Settlements]
                              ...                        
9098    [Natural Disasters, Monetary and Economic Policy]
9099                                            [IT Risk]
9100                                  [Natural Disasters]
9101    [Financial Accounting, IT Risk, Corporate Comm...
9102    [Monetary and Economic Policy, Natural Disaste...
Name: cat_name, Length: 9103, dtype: object


In [88]:
from sklearn.preprocessing import MultiLabelBinarizer
import numpy as np


mlb = MultiLabelBinarizer()
Y = mlb.fit_transform(labels)

# check size of indicator matrix
# print some rows 
Y[0]
Y.shape
# check classes
mlb.classes_

# check # of samples in each class
np.sum(Y, axis=0)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0])

(9103, 50)

array(['Accounting and Finance', 'Antitrust', 'Banking', 'Broker Dealer',
       'Commodities Trading', 'Compliance Management',
       'Consumer protection', 'Contract Provisions',
       'Corporate Communications', 'Corporate Governance', 'Definitions',
       'Delivery', 'Examinations', 'Exemptions', 'Fees and Charges',
       'Financial Accounting', 'Financial Crime', 'Forms', 'Fraud',
       'IT Risk', 'Information Filing', 'Insurance', 'Legal',
       'Legal Proceedings', 'Licensing', 'Licensure and certification',
       'Liquidity Risk', 'Listing', 'Market Abuse', 'Market Risk',
       'Monetary and Economic Policy', 'Money Services',
       'Money-Laundering and Terrorist Financing', 'Natural Disasters',
       'Payments and Settlements', 'Powers and Duties', 'Quotation',
       'Records Maintenance', 'Regulatory Actions',
       'Regulatory Reporting', 'Required Disclosures', 'Research',
       'Risk Management', 'Securities Clearing', 'Securities Issuing',
       'Securities

array([ 869,  779,  984,  626,  601, 1242,  889, 1052,  490,  811,  494,
        756, 1515, 1127, 1173,  494, 1086,  473,  829,  384, 1227,  685,
        785, 1210,  938,  935,  483,  992,  667, 1470,  742,  770,  457,
        986,  975,  692,  557,  577, 1448,  923,  575,  489,  881, 1039,
       1023,  616, 1591,  759,  774,  651])

In [ ]:
pip install xgboost

In [89]:
import numpy as np
import xgboost
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.svm import LinearSVC
from xgboost import XGBClassifier
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.model_selection import train_test_split
from sklearn.multiclass import OneVsRestClassifier
from sklearn.metrics import classification_report
from sklearn.feature_extraction.text import TfidfVectorizer

In [101]:
# Multi-label classification- one vs. rest classifier
from sklearn.linear_model import SGDClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn import svm
from sklearn.neural_network import MLPClassifier
from sklearn.utils import class_weight

mlp=MLPClassifier(random_state=0, early_stopping=True, verbose=2)
sgd = SGDClassifier(random_state=0,loss='log',alpha=0.01,penalty='elasticnet')
lr = LogisticRegression(C=1.0)
svc = svm.LinearSVC()
nb = MultinomialNB()
xgb = XGBClassifier(scale_pos_weight=4)
X_train, X_test, Y_train, Y_test = train_test_split(\
                data4, Y, test_size=0.3, random_state=0)

classes_weights = class_weight.compute_sample_weight(
    class_weight='balanced',
    y=Y_train
)

classifier = Pipeline([
    ('tfidf', TfidfVectorizer(min_df=1,stop_words="english")),
    ('clf', OneVsRestClassifier(estimator=xgb))])

#kwargs = {classifier.steps[-1][0] + '__sample_weight': classes_weights}
#classifier.fit(X_train, Y_train, **kwargs)

classifier.fit(X_train, Y_train)

Pipeline(steps=[('tfidf', TfidfVectorizer(stop_words='english')),
                ('clf',
                 OneVsRestClassifier(estimator=XGBClassifier(base_score=None,
                                                             booster=None,
                                                             callbacks=None,
                                                             colsample_bylevel=None,
                                                             colsample_bynode=None,
                                                             colsample_bytree=None,
                                                             early_stopping_rounds=None,
                                                             enable_categorical=False,
                                                             eval_metric=None,
                                                             gamma=None,
                                                             gpu_id=None,
                         

In [102]:
from sklearn.metrics import classification_report

predicted = classifier.predict(X_test)

predicted.shape
print("predicted:")
predicted[0:2]
print("actual:")
Y_test[0:2]

print(classification_report\
      (Y_test, predicted, target_names=mlb.classes_))

(2731, 50)

predicted:


array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0]])

actual:


array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0]])

                                          precision    recall  f1-score   support

                  Accounting and Finance       0.81      0.70      0.75       269
                               Antitrust       0.87      0.79      0.83       219
                                 Banking       0.93      0.86      0.89       322
                           Broker Dealer       0.86      0.82      0.84       167
                     Commodities Trading       0.92      0.92      0.92       179
                   Compliance Management       0.83      0.95      0.89       354
                     Consumer protection       0.91      0.86      0.89       274
                     Contract Provisions       0.83      0.85      0.84       333
                Corporate Communications       0.84      0.50      0.63       157
                    Corporate Governance       0.77      0.52      0.62       236
                             Definitions       0.75      0.93      0.83       135
               

In [92]:
#PREDICTING ON TEST DATA

# Multi-label classification- Performance report

from sklearn.metrics import classification_report

predicted = classifier.predict(test_doc)

predicted.shape
print("predicted:")
predicted[0:2]

#print(classification_report\
 #     (Y_test, predicted, target_names=mlb.classes_))

(4993, 50)

predicted:


array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0]])

In [93]:
#submission output
final_id=[]
label_list=[]
predicted_list=[]
ids=test['id']
for i in ids:
    for j in range(0,50):
        final_id.append(i)
    for k in mlb.classes_:
        label_list.append(k)
for l in predicted:
     for m in l: 
        predicted_list.append(m)

In [94]:
zipped = list(zip(final_id,label_list,predicted_list))

output_df=pd.DataFrame(zipped, columns=['ID', 'LABEL', 'predictions'])
output_df["id"] = output_df["ID"].astype(str) + '_' + output_df["LABEL"]

In [95]:
final_output = output_df[['id', 'predictions']]
final_output

id  predictions
0       4771_Accounting and Finance            1
1                    4771_Antitrust            0
2                      4771_Banking            0
3                4771_Broker Dealer            0
4          4771_Commodities Trading            0
...                             ...          ...
249645  57235_Securities Management            0
249646       57235_Securities Sales            0
249647  57235_Securities Settlement            0
249648          57235_Trade Pricing            0
249649       57235_Trade Settlement            0

[249650 rows x 2 columns]

In [96]:
final_output.to_csv('submission.csv', index=False)